cache:
  paths:
  - node_modules/

stages:
  - lint
  - deploy

eslint:
  stage: lint
  script:
    - npm install
    - npm run lint
  only:
     - triggers
  tags:
    - pp-projects

deploy:
  stage: deploy
  script:
    - cd /home/devuser/DevProjects/645.echo_web/desktop
    - git pull origin master
    - npm install
    - npm run build-dev
  only:
    - master
  tags:
    - pp-projects
