cache:
  paths:
  - node_modules/

stages:
  - lint
  - prepare
  - deploy

eslint:
  stage: lint
  script:
    - npm install
    - npm run lint
  only:
     - triggers
     - develop
     - master
     - merge_requests
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - cd /home/devuser/DevProjects/645.echo_web/desktop
    - git pull origin master
    - npm install
    - npm run build-dev
  only:
    - master
  tags:
    - pp-projects

build.macos:
  stage: prepare
  script:
    - npm install
    - npm run package-mac
  only:
    - web
    - tags
  tags:
    - echo-mac
  artifacts:
     paths:
     - build/binaries/ECHO Wallet-1.2.5.dmg
     expire_in: 1 week


build.linux:
  stage: prepare
  script:
    - rm  -rf node_modules/
    - npm install
    - npm run package-deb
  only:
    - web
    - tags
  tags:
    - echo-linux
  artifacts:
     paths:
     - build/binaries/ECHOWallet_1.2.5_amd64.deb
     expire_in: 1 week

build.windows:
  stage: prepare
  script:
    - npm install
    - npm run package-win
  only:
    - web
    - tags
  tags:
    - echo-linux
  artifacts:
     paths:
     - build/binaries/ECHO Wallet Setup 1.2.5.exe
     expire_in: 1 week

build.linux-debug:
  stage: prepare
  script:
    - npm install
    - npm run package-deb-debug
  only:
    - web
  tags:
    - echo-linux
  artifacts:
     paths:
     - build/binaries/ECHOWallet_1.2.5_amd64.deb
     expire_in: 1 week

build.windows-debug:
  stage: prepare
  script:
    - npm install
    - npm run package-win-debug
  only:
    - web
  tags:
    - echo-linux
  artifacts:
     paths:
     - build/binaries/ECHO Wallet Setup 1.2.5.exe
     expire_in: 1 week
