cache:
  paths:
  - node_modules/

stages:
  - lint
  - prepare
  - deploy

eslint:
  stage: lint
  script:
    - npm install
    - npm run lint
  only:
     - triggers
  tags:
    - pp-projects

deploy:
  stage: deploy
  script:
    - cd /home/devuser/DevProjects/645.echo_web/desktop
    - git pull origin master
    - npm install
    - npm run build-dev
  only:
    - master
  tags:
    - pp-projects

build.macos:
  stage: deploy
  script:
    - npm install
    - npm run package-mac
  only:
    - web
    - tags
  tags:
    - echo-mac
  artifacts:
     paths:
     - build/binaries/ECHO Wallet-0.9.0.dmg
     expire_in: 1 week


build.linux:
  stage: deploy
  script:
    - rm  -rf node_modules/
    - rm package-lock.json
    - npm install
    - npm run package-deb
  only:
    - web
    - tags
  tags:
    - echo-linux
  artifacts:
     paths:
     - build/binaries/ECHOWallet_0.9.0_amd64.deb
     expire_in: 1 week

build.windows:
  stage: deploy
  script:
    - npm install
    - npm run package-win
  only:
    - web
    - tags
  tags:
    - echo-linux
  artifacts:
     paths:
     - build/binaries/ECHO Wallet Setup 0.9.0.exe.blockmap
     expire_in: 1 week

build.linux-debug:
  stage: deploy
  script:
    - npm install
    - npm run package-deb-debug
  only:
    - web
  tags:
    - echo-linux
  artifacts:
     paths:
     - build/binaries/ECHOWallet_0.9.0_amd64.deb
     expire_in: 1 week

build.windows-debug:
  stage: deploy
  script:
    - npm install
    - npm run package-win-debug
  only:
    - web
  tags:
    - echo-linux
  artifacts:
     paths:
     - build/binaries/ECHO Wallet Setup 0.9.0.exe.blockmap
     expire_in: 1 week
