#stages:
#  - lint
#  - deploy
#
#eslint:
#  stage: lint
#  script:
#    - npm i
#    - npm run lint
#
#build_dev:
#  stage: deploy
#  script:
#    - cd /var/www/Projects/i/web-ui
#    - git pull
#    - npm i
#    - npm run build-dev
#  only:
#    - development
#  environment:
#    name: development
#  tags:
#    - pp-dev
