stages:
  - build
  - deploy


build:
  stage: build
  variables:
    NODE_APP_INSTANCE: $CI_COMMIT_REF_NAME
  before_script:
    - export CI_COMMIT_REF_NAME=develop
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --cache-from $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - master
    - develop
    - EDW-497
  tags:
    - echo-linux


deploy:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - export CI_COMMIT_REF_NAME=develop
    - if [ "$CI_COMMIT_REF_NAME" != "master" ]; then export PORT=36450; fi
  variables:
    CI_FULL_REGISTRY: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    PORT: 26450
  script:
    - docker-compose -p $CI_COMMIT_REF_NAME up -d
  only:
    - develop
    - master
    - EDW-497
  tags:
    - echo-linux
