stages:
  - test
  - build
  - deploy

test:
  image: node:10
  stage: test
  cache:
    paths:
      - node_modules/
  script:
    - npm i
    - npm run lint
  tags:
    - docker
  only:
    - merge_requests

build:
  stage: build
  variables:
    NODE_APP_INSTANCE: $CI_COMMIT_REF_NAME
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME --build-arg CRYPTO_API_KEY=${CRYPTO_API_KEY} .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - master
    - develop
  tags:
    - echo-linux

deploy:
  stage: deploy
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - if [ "$CI_COMMIT_REF_NAME" != "master" ]; then export PORT=36450; fi
  variables:
    CI_FULL_REGISTRY: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    PORT: 26450
  script:
    - docker-compose -p $CI_COMMIT_REF_NAME pull
    - docker-compose -p $CI_COMMIT_REF_NAME up -d
  only:
    - develop
    - master
  tags:
    - echo-linux

build:macos:
  image: node:10
  stage: build
  variables:
    DOWNLOAD_ECHO_NODE_URL: "https://echo-bin.s3.eu-central-1.amazonaws.com/echo-macos..tar"
    NODE_APP_INSTANCE: $CI_COMMIT_REF_NAME
  artifacts:
    paths:
      - ./build/binaries/Echo*.dmg
  script:
    - rm -rf node_modules
    - npm i
    - npm run package-mac-with-download-build
  only:
    - master
    - develop
  tags:
    - echo-macos-clean
