language: node_js
node_js:
  - "10"

stages:
  - test
  - build

jobs:
  include:

    - stage: test
      name: "Lint"
      if: type = push
      script:
        - npm run lint

    - stage: build
      name: "Gitlab Mirror Trigger"
      if: type = push
      before_script:
        - sudo apt-get install -y curl
      script:
        - "curl --request POST --header \"PRIVATE-TOKEN: ${GITLAB_TOKEN}\" https://gitlab.com/api/v4/projects/13691195/mirror/pull"

    - stage: build
      name: "Build Linux App"
      if: tag IS present
      script:
        - npm run package-deb
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: build/binaries/echo-wallet*
        skip_cleanup: true
        on:
          tags: true

    - stage: build
      name: "Build Win App"
      if: tag IS present
      script:
        - npm run package-win
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: build/binaries/Echo*
        skip_cleanup: true
        on:
          tags: true

    - stage: build
      os: osx
      name: "Build macOS App"
      if: tag IS present
      script:
        - npm run package-mac
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true
        file: build/binaries/Echo*
        skip_cleanup: true
        on:
          tags: true
